### ISSUE TITLE
>2023-05 Breaking Changes ?

### ISSUE THREAD

**Issue by HollyFredD** [godely/ha-dremel-3d-printer#1]
Hi,

I've been using your custom_component for weeks without any trouble but it looks like starting 2023_05 is doesn't work anymore  : "failed to setup"

Here is what I have in the log output : 
```
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dremel_3d_printer/__init__.py", line 73, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Could you get a look a it ?
Thanks,
Frederic

**Comment by JayBomb999** [comment]
> Hi,
> 
> I've been using your custom_component for weeks without any trouble but it looks like starting 2023_05 is doesn't work anymore : "failed to setup"
> 
> Here is what I have in the log output :
> 
> ```
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dremel_3d_printer/__init__.py", line 73, in async_setup_entry
>     hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
> ```
> 
> Could you get a look a it ? Thanks, Frederic

Forgive the "me too" post, but I am having the exact same issue.

**Comment by HollyFredD** [comment]
The below fork is fixed and works with HA >2023.05 : 
https://github.com/nbetcher/ha-dremel-3d-printer

**Comment by Tontze** [comment]
> The below fork is fixed and works with HA >2023.05 : https://github.com/nbetcher/ha-dremel-3d-printer

Is there something else to do when installing that fork more than using hacs ? Since it does not seem to be working with my 3D40 ..

**Comment by godely** [comment]
This is now an official integration on Home Assistant (https://www.home-assistant.io/integrations/dremel_3d_printer/). Is there something you get out from this HACS component that is not available there? Let me know and I'll add. Nevertheless, thanks for the fix @nbetcher, I'll rebase this repo based on your fix.

**Comment by nbetcher** [comment]
> This is now an official integration on Home Assistant (https://www.home-assistant.io/integrations/dremel_3d_printer/). Is there something you get out from this HACS component that is not available there? Let me know and I'll add. Nevertheless, thanks for the fix @nbetcher, I'll rebase this repo based on your fix.

I had no idea it was in Home Assistant now, although it wasn't at the time (introduced in July, my change was made in May).

@HollyFredD Nice catch on my fork btw. ;)
